FROM ubuntu:latest
RUN apt update && apt install  openssh-server sudo -y && apt install iputils-ping -y
RUN groupadd sshgroup && useradd -ms /bin/bash -g sshgroup sshuser
RUN echo sshuser:test | chpasswd
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]