version: '3'

services:
  haproxy:
    image: imageName
  web:
    image: ngnix
    container_name: ngnix1
    ports:
      - "8001:80"
    environment: 
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      # Volume stockant les fichiers web du projet
      - NGNIX/WEB_SITE/:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
