FROM haproxy
USER root
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

RUN apt -y update \
    && apt-get upgrade -y \
    && apt install keepalived -y
# CMD [ "cat /etc/keepalived/keepalived.conf" ]
