FROM haproxytech/haproxy-alpine
USER root
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

#RUN ls /etc/haproxy/
#CMD [ "ping 8.8.8.8" ]
#RUN apt -y update \
#    && apt-get upgrade -y \
#    && apt install keepalived -y
# CMD [ "cat /etc/keepalived/keepalived.conf" ]
