version: '3.8'

services:
  wordpress:
    build: 
      context: .
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - network_wordpress

  db:
    image: mysql:oracle
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
    #volumes:
    #  - db_data:/var/lib/mysql
    networks:
      - network_wordpress


#volumes:
#  db_data:

networks:
  network_wordpress: